spring:
  application:
    name: hospital-management-system

  datasource:
    url: jdbc:mysql://localhost:3306/hospital_management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
    username: root
    password: M.Utkarsh
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

app:
  jwt:
    secret: "HMS-7fK9vQ2xL8mN4pR6tY1wZ5aC3dE8gH0jK2sV9bX6nM4qP7"
    expiration-ms: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.jdbc: DEBUG
    com.utkarsh2573.backend: DEBUG